version: '2'
services:
  python:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./girls_tutorial:/usr/src/girls_tutorial
    command: python girls_tutorial/manage.py runserver 0.0.0.0:8000